-- INSERT INTO film (title, boxoffice, duration, description, premiere_year) VALUES ('Forrest Gump',
--   677387716,
--   144,
--   'Historia życia Forresta, chłopca o niskim ilorazie inteligencji z niedowładem kończyn, który staje się miliarderem i bohaterem wojny w Wietnamie.',
--   1994);
-- INSERT INTO film (title, boxoffice, duration, description, premiere_year) VALUES ('Shawshank Redemption',
-- 59841469,
-- 144,
-- 'Adaptacja opowiadania Stephena Kinga. Niesłusznie skazany na dożywocie bankier, stara się przetrwać w brutalnym, więziennym świecie.',
-- 1994);
-- INSERT INTO actor (first_name, last_name, height, description, born_year, born_place) VALUES ('Tom',
-- 'Hanks',
--  183,
-- 'Jego rodzice rozwiedli się, gdy miał pięć lat. Wychowywał go ojciec – kucharz, który wkrótce przeniósł się z Kaliforni do Oakland. Aktorstwem Tom zainteresował się w szkole średniej.',
--   1956,
--   'Concord, Kalifornia, USA');
-- INSERT INTO roles(name) VALUES('ROLE_USER');
-- INSERT INTO roles(name) VALUES('ROLE_ADMIN');
