-- INSERT INTO film (title, boxoffice, duration) VALUES ('Forrest Gump', 500000, 120);
-- INSERT INTO film (title, boxoffice, duration) VALUES ('Shawshank Redemption', 500, 150);
-- INSERT INTO actor (first_name, last_name, height) VALUES ('Tom', 'Hanks', 180);
-- INSERT INTO roles(name) VALUES('ROLE_USER');
-- INSERT INTO roles(name) VALUES('ROLE_ADMIN');